INSERT INTO product VALUES(1,'Birra alla spina 300 cl','bar',4.0);
INSERT INTO product VALUES(2,'Coca Cola 50 cl','bar',2.5);
INSERT INTO product VALUES(3,'Fanta 33 cl','bar',3.0);
INSERT INTO product VALUES(4,'Sprite 33 cl','bar',3.0);
INSERT INTO product VALUES(5,'The 33 cl','bar',3.0);
INSERT INTO product VALUES(6,'Acqua frizzante 50 cl','bar',1.0);
INSERT INTO product VALUES(7,'Acqua naturale 50 cl','bar',1.0);
INSERT INTO product VALUES(8,'Vino bianco al bicchiere','bar',1.5);
INSERT INTO product VALUES(9,'Vino rosso al bicchiere','bar',1.5);
INSERT INTO product VALUES(10,'Vino bianco 1 L','bar',10.0);
INSERT INTO product VALUES(11,'Vino rosso 1 L','bar',10.0);
INSERT INTO product VALUES(12,'Caffe','dessert',1.0);
INSERT INTO product VALUES(13,'Gnocco fritto','cucina',3.5);
INSERT INTO product VALUES(14,'Patatine fritte','cucina',3.5);
INSERT INTO product VALUES(15,'Tagliere salumi','cucina',7.0);
INSERT INTO product VALUES(16,'Panino con hamb. 150g','cucina',5.0);
INSERT INTO product VALUES(17,'Panino con salamella','cucina',4.0);
INSERT INTO product VALUES(18,'Panino con coppa','cucina',4.0);
INSERT INTO product VALUES(19,'Panino con salame','cucina',4.0);
INSERT INTO product VALUES(20,'Panino con pros. cotto','cucina',4.0);
INSERT INTO product VALUES(21,'Panino con mortadella','cucina',4.0);
